### ISSUE TITLE
Simplify script?

### ISSUE THREAD

**Issue by kshyatt** [timholy/CoverageBase.jl#13]
Since the `.cov` files now contain PIDs, there's no danger of overwriting the inlined results with no-inline results. Could we dramatically simplify the coverage scripts this way? We'd only have to make one coverage report and wouldn't need `merge_coverage` any more.

**Comment by timholy** [comment]
Sounds good to me. If I remember correctly, didn't you move most of the merge functionality into `Coverage.jl` anyway?
