### ISSUE TITLE
remove external package code from coverage

### ISSUE THREAD

**Issue by vtjnash** [timholy/CoverageBase.jl#36]
Currently we report coverage statistics for files such as stdlib/Pkg/*, even though those files don't exist in the repository. Since we don't run their tests either (and couldn't even tell you what lines were impacted if we did), we should likely filter those out.

**Comment by vtjnash** [comment]
We do exclude Pkg, but other packages (like LibGit2) are not getting excluded

**Comment by vtjnash** [comment]
This might be urgent priority now. The combination of lots of jll files, and 12k new autogenerated lines in SuiteSparse that can't be tested (#40804) are leading to incorrectly computed statistics overall now (https://codecov.io/gh/JuliaLang/julia/compare/6f71de4193717f9267e98b4188aa6e4547146375...ed5cc4ec674a2900f7a1d2f0937726bd61e694ca/tree)

**Comment by DilumAluthge** [comment]
I think https://github.com/JuliaCI/julia-buildbot/pull/207 is actually going to be the best fix for this solution, since it does not require that we hard-code a list of external stdlibs.
