### ISSUE TITLE
Adding `pkg` to testnames

### ISSUE THREAD

**Issue by staticfloat** [timholy/CoverageBase.jl#4]
@timholy After merging the selection of testnames into base Julia, we have discovered a test that we want to run in the coverage suite; `pkg`.  Should we change `choosetests.jl` to include an option that we can set somehow to ensure `pkg` gets run, or should we add some logic here to get that test to run?  We already run the `pkg` test [manually on travis](https://github.com/JuliaLang/julia/blob/master/.travis.yml#L65).

**Comment by timholy** [comment]
I guess the reason it's not part of the regular test suite is to prevent spurious failures in not-connected systems? I wasn't involved in that decision, so I'm only guessing.

I don't really have strong feelings about how it should be implemented. If you want to tweak stuff here, that's fine with me. (I'm also happy transferring this package to you or julialang, if that's preferable.)

**Comment by staticfloat** [comment]
Yes, precisely.  It fails on things like Canonical's buildd servers, because those do not have internet connectivity.

Since you don't have strong feelings about it, (and with my new god-like push powers to this repo) I'll just write something that I can live with.  Thanks!

**Comment by timholy** [comment]
Enjoy it, new god :smile:. You have some recent companions, too.

**Comment by kshyatt** [comment]
Now I can try to figure out why my Coveralls is showing 60% coverage, while the JuliaLang one is correctly showing 76%. Bizarre.

**Comment by kshyatt** [comment]
I ran my own Coveralls with `pkg` enabled - it should bump us up to ~77.5%

**Comment by timholy** [comment]
Closed by b3b061563c28babc4a1115777ac33c2b48acd487
