### ISSUE TITLE
Upload coverage reports even if some CI checks fail

### ISSUE THREAD

**Issue by bramtayl** [timholy/CoverageBase.jl#44]
I'm not talking about coverage reports from PRs, but coverage reports from commits. It looks like the last time coverage was uploaded from master was 07 Oct 2020 02:42AM UTC if I'm reading it correctly? Ref https://github.com/JuliaCI/julia-buildbot/issues/173

**Comment by vtjnash** [comment]
Coverage reports are already uploaded regardless of CI status (not for every commit, since the builder takes awhile, but on a rolling basis)

**Comment by bramtayl** [comment]
Ok, sorry for the hassle
